# Generated by Django 3.0.8 on 2020-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20200804_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='path',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
